<?php

namespace App\Http\Requests\Cart;

use App\Rules\quantityRule;
use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'quantity'=>['required' , new quantityRule() ] ,
            'color'=>'required' ,
            'size'=>'required'
        ];
    }
    public function messages()
    {
        return [
            'color.required'=>'please Choose The Color ' ,
            'size.required'=>'please Choose The size ' ,

        ] ;
        // TODO: Change the autogenerated stub
    }
}
